/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.pptx.validation

import com.google.common.collect.Maps
import org.eclipse.xtext.validation.Check
import org.xtext.example.pptx.pptx.PptxPackage
import org.xtext.example.pptx.pptx.Presentation

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class PptxValidator extends AbstractPptxValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					PptxPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check
	def checkSlideReferencesByPresentation(Presentation presentation) {
		val map = Maps.newHashMap
		for(slide : presentation.slides) {
			var count = map.get(slide)
			if (count === null)  count = 0
			map.put(slide, count+1)
		}
		for(i : 0 ..< presentation.slides.size) {
			val slide = presentation.slides.get(i)
			if (map.get(slide) > 1) {
				warning("Slide is contained in presentation more than once", presentation, PptxPackage.eINSTANCE.presentation_Slides, i)
			}
		}
	}
}
