/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.pptx.pptx.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.pptx.pptx.Model;
import org.xtext.example.pptx.pptx.PptxPackage;
import org.xtext.example.pptx.pptx.Presentation;
import org.xtext.example.pptx.pptx.SlideContent;
import org.xtext.example.pptx.pptx.Theme;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.pptx.pptx.impl.ModelImpl#getContents <em>Contents</em>}</li>
 *   <li>{@link org.xtext.example.pptx.pptx.impl.ModelImpl#getPresentations <em>Presentations</em>}</li>
 *   <li>{@link org.xtext.example.pptx.pptx.impl.ModelImpl#getThemes <em>Themes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelImpl extends MinimalEObjectImpl.Container implements Model
{
  /**
   * The cached value of the '{@link #getContents() <em>Contents</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContents()
   * @generated
   * @ordered
   */
  protected EList<SlideContent> contents;

  /**
   * The cached value of the '{@link #getPresentations() <em>Presentations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPresentations()
   * @generated
   * @ordered
   */
  protected EList<Presentation> presentations;

  /**
   * The cached value of the '{@link #getThemes() <em>Themes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThemes()
   * @generated
   * @ordered
   */
  protected EList<Theme> themes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PptxPackage.Literals.MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SlideContent> getContents()
  {
    if (contents == null)
    {
      contents = new EObjectContainmentEList<SlideContent>(SlideContent.class, this, PptxPackage.MODEL__CONTENTS);
    }
    return contents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Presentation> getPresentations()
  {
    if (presentations == null)
    {
      presentations = new EObjectContainmentEList<Presentation>(Presentation.class, this, PptxPackage.MODEL__PRESENTATIONS);
    }
    return presentations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Theme> getThemes()
  {
    if (themes == null)
    {
      themes = new EObjectContainmentEList<Theme>(Theme.class, this, PptxPackage.MODEL__THEMES);
    }
    return themes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PptxPackage.MODEL__CONTENTS:
        return ((InternalEList<?>)getContents()).basicRemove(otherEnd, msgs);
      case PptxPackage.MODEL__PRESENTATIONS:
        return ((InternalEList<?>)getPresentations()).basicRemove(otherEnd, msgs);
      case PptxPackage.MODEL__THEMES:
        return ((InternalEList<?>)getThemes()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PptxPackage.MODEL__CONTENTS:
        return getContents();
      case PptxPackage.MODEL__PRESENTATIONS:
        return getPresentations();
      case PptxPackage.MODEL__THEMES:
        return getThemes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PptxPackage.MODEL__CONTENTS:
        getContents().clear();
        getContents().addAll((Collection<? extends SlideContent>)newValue);
        return;
      case PptxPackage.MODEL__PRESENTATIONS:
        getPresentations().clear();
        getPresentations().addAll((Collection<? extends Presentation>)newValue);
        return;
      case PptxPackage.MODEL__THEMES:
        getThemes().clear();
        getThemes().addAll((Collection<? extends Theme>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PptxPackage.MODEL__CONTENTS:
        getContents().clear();
        return;
      case PptxPackage.MODEL__PRESENTATIONS:
        getPresentations().clear();
        return;
      case PptxPackage.MODEL__THEMES:
        getThemes().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PptxPackage.MODEL__CONTENTS:
        return contents != null && !contents.isEmpty();
      case PptxPackage.MODEL__PRESENTATIONS:
        return presentations != null && !presentations.isEmpty();
      case PptxPackage.MODEL__THEMES:
        return themes != null && !themes.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ModelImpl
