/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.pptx;

import org.xtext.example.pptx.AbstractPptxRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PptxRuntimeModule extends AbstractPptxRuntimeModule {
}
