/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.pptx.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.pptx.ui.AbstractPptxUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PptxUiModule extends AbstractPptxUiModule {
  public PptxUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
