/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.pptx.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPptxScopeProvider extends DelegatingScopeProvider {
}
