/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.pptx.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.pptx.ui.internal.PptxActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PptxExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(PptxActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		PptxActivator activator = PptxActivator.getInstance();
		return activator != null ? activator.getInjector(PptxActivator.ORG_XTEXT_EXAMPLE_PPTX_PPTX) : null;
	}

}
