/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.abppt.abppt;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Presentation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.abppt.abppt.Presentation#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.abppt.abppt.Presentation#getTheme <em>Theme</em>}</li>
 *   <li>{@link org.xtext.example.abppt.abppt.Presentation#getSlides <em>Slides</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.abppt.abppt.AbpptPackage#getPresentation()
 * @model
 * @generated
 */
public interface Presentation extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.abppt.abppt.AbpptPackage#getPresentation_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.abppt.abppt.Presentation#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Theme</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Theme</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Theme</em>' reference.
   * @see #setTheme(Theme)
   * @see org.xtext.example.abppt.abppt.AbpptPackage#getPresentation_Theme()
   * @model
   * @generated
   */
  Theme getTheme();

  /**
   * Sets the value of the '{@link org.xtext.example.abppt.abppt.Presentation#getTheme <em>Theme</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Theme</em>' reference.
   * @see #getTheme()
   * @generated
   */
  void setTheme(Theme value);

  /**
   * Returns the value of the '<em><b>Slides</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.abppt.abppt.SlideContent}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Slides</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Slides</em>' reference list.
   * @see org.xtext.example.abppt.abppt.AbpptPackage#getPresentation_Slides()
   * @model
   * @generated
   */
  EList<SlideContent> getSlides();

} // Presentation
