/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.pptx.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.pptx.PptxRuntimeModule
import org.xtext.example.pptx.PptxStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class PptxIdeSetup extends PptxStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new PptxRuntimeModule, new PptxIdeModule))
	}
	
}
