/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.abppt.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.abppt.parser.antlr.internal.InternalAbpptParser;
import org.xtext.example.abppt.services.AbpptGrammarAccess;

public class AbpptParser extends AbstractAntlrParser {

	@Inject
	private AbpptGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAbpptParser createParser(XtextTokenStream stream) {
		return new InternalAbpptParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public AbpptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AbpptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
