/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.abppt.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AbpptAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/abppt/parser/antlr/internal/InternalAbppt.tokens");
	}
}
