/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.abppt.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.abppt.ui.internal.AbpptActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AbpptExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(AbpptActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		AbpptActivator activator = AbpptActivator.getInstance();
		return activator != null ? activator.getInjector(AbpptActivator.ORG_XTEXT_EXAMPLE_ABPPT_ABPPT) : null;
	}

}
