/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.pptx.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PptxAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/pptx/parser/antlr/internal/InternalPptx.tokens");
	}
}
