/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.pptx.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.pptx.parser.antlr.internal.InternalPptxParser;
import org.xtext.example.pptx.services.PptxGrammarAccess;

public class PptxParser extends AbstractAntlrParser {

	@Inject
	private PptxGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPptxParser createParser(XtextTokenStream stream) {
		return new InternalPptxParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public PptxGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PptxGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
