/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.abppt.ide;

import org.xtext.example.abppt.ide.AbstractAbpptIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AbpptIdeModule extends AbstractAbpptIdeModule {
}
