/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.abppt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.abppt.ui.AbstractAbpptUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AbpptUiModule extends AbstractAbpptUiModule {
  public AbpptUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
