/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.abppt;

import org.xtext.example.abppt.AbpptStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AbpptStandaloneSetup extends AbpptStandaloneSetupGenerated {
  public static void doSetup() {
    new AbpptStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
