/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.abppt;

import org.xtext.example.abppt.AbstractAbpptRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AbpptRuntimeModule extends AbstractAbpptRuntimeModule {
}
