/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.abppt


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AbpptRuntimeModule extends AbstractAbpptRuntimeModule {
}
