/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.abppt


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AbpptStandaloneSetup extends AbpptStandaloneSetupGenerated {

	def static void doSetup() {
		new AbpptStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
