/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.pptx.ide;

import org.xtext.example.pptx.ide.AbstractPptxIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PptxIdeModule extends AbstractPptxIdeModule {
}
