/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.pptx.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.pptx.PptxRuntimeModule;
import org.xtext.example.pptx.PptxStandaloneSetup;
import org.xtext.example.pptx.ide.PptxIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class PptxIdeSetup extends PptxStandaloneSetup {
  @Override
  public Injector createInjector() {
    PptxRuntimeModule _pptxRuntimeModule = new PptxRuntimeModule();
    PptxIdeModule _pptxIdeModule = new PptxIdeModule();
    return Guice.createInjector(Modules2.mixin(_pptxRuntimeModule, _pptxIdeModule));
  }
}
